### ISSUE TITLE
import failures

### ISSUE THREAD

**Issue by ITmustang** [SpiderLabs/portia#2]
this is one of the few errors im getting after install. i have gotten 

root@kali:/opt/portia# ./portia.py 
Traceback (most recent call last):
  File "./portia.py", line 16, in <module>
    import nmap
ImportError: No module named nmap

i installed python-nmap and i believe i fixed that as it hasnt re-appeared.

as well as 

root@kali:/opt/portia# ./portia.py 
Traceback (most recent call last):
  File "./portia.py", line 9, in <module>
    from deps.secretsdump import *
  File "/opt/portia/deps/secretsdump.py", line 56, in <module>
    from impacket.examples.secretsdump import LocalOperations, RemoteOperations, SAMHashes, LSASecrets, NTDSHashes
ImportError: No module named secretsdump

**Comment by milo2012** [comment]
Regarding the below error.
ImportError: No module named secretsdump

Did you happen to install impacket or run install.sh to install the dependencies ?Thanks
cd /opt
git clone https://github.com/CoreSecurity/impacket
python setup.py install

**Comment by ITmustang** [comment]
i had CoreSecurity/impacket installed previously for another programs pre-reqs. but i removed it and installed the impacket from within the install.sh. (i installed everything manully i didnt run the install.sh as i was originally having the above metioned issues.

**Comment by ITmustang** [comment]
-quick update... erased impacket folder and reinstalled using 
"cd /opt
git clone https://github.com/CoreSecurity/impacket
python setup.py install' ......not sure what changed as i had done this before, but i wont knock it.
-verified it was 'apt-get install python-nmap' that was needed.
i run program....and it loads without error. 

root@kali:/opt/portia# ./portia.py 
usage: PROG [-h] [-d DOMAIN] [-u USERNAME] [-p PASSWORD] [-s] [-L] [-amsi]
            [-bypass] [-obfs] [-M MODULE]
            [-o MODULE_OPTION [MODULE_OPTION ...]] [-D]
            [target [target ...]]
-closing issue..
